# 1. COLOQUE AQUI A SUA URL EXTERNA DO RENDER (lembre de mudar o início para jdbc:postgresql://)
spring.datasource.url=jdbc:postgresql://USUARIO:SENHA@HOST_DO_RENDER.com/bookstore

# 2. COLOQUE AQUI O USUÁRIO E A SENHA QUE APARECEM NO PAINEL DO BANCO DO RENDER
spring.datasource.username=seu_usuario_do_render
spring.datasource.password=sua_senha_do_render

# Configurações do Hibernate para criar as tabelas na nuvem
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect